name: CI & Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: echo "Skipping tests"   # Dummy test, replace with real tests later

      - name: Build project
        run: npm run build
        env:
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
          CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
          NEXT_PUBLIC_CLERK_SIGN_UP_URL: ${{ secrets.NEXT_PUBLIC_CLERK_SIGN_UP_URL }}
          NEXT_PUBLIC_CLERK_SIGN_IN_URL: ${{ secrets.NEXT_PUBLIC_CLERK_SIGN_IN_URL }}
          NEXT_PUBLIC_DRIZZLE_DB_URL: ${{ secrets.NEXT_PUBLIC_DRIZZLE_DB_URL }}
          NEXT_PUBLIC_GEMINI_API_KEY: ${{ secrets.NEXT_PUBLIC_GEMINI_API_KEY }}
          NEXT_PUBLIC_INTERVIEW_QUESTION_COUNT: ${{ secrets.NEXT_PUBLIC_INTERVIEW_QUESTION_COUNT }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Trigger Vercel Deployment
        run: curl -X POST ${{ secrets.VERCEL_DEPLOY_HOOK }}
